export interface SoftwareTemplate {
  id: string;
  name: string;
  vendor: string;
  product: string;
  category: 'A' | 'B' | 'C';
  supportedOs: ('Windows' | 'MacOS' | 'Ubuntu' | 'Linux')[];
  defaultSeverity: string;
  defaultCategory: string;
  apiUrl: string;
  parserId: string;
  hubCategory?: string; // browser, utility, development, runtime, security, productivity, communication, media, enterprise
  description?: string;
  referenceUrl?: string;
}

export const SOFTWARE_CATALOG: SoftwareTemplate[] = [
  // ---- Category A: Fully Automatic (JSON/REST APIs) ----
  {
    id: 'nodejs',
    name: 'Node.js',
    vendor: 'OpenJS Foundation',
    product: 'Node.js',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://nodejs.org/dist/index.json',
    parserId: 'nodejs',
    hubCategory: 'runtime',
    referenceUrl: 'https://nodejs.org/',
  },
  {
    id: 'golang',
    name: 'Go',
    vendor: 'Google',
    product: 'Go',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://go.dev/dl/?mode=json',
    parserId: 'golang',
    hubCategory: 'runtime',
    referenceUrl: 'https://go.dev/',
  },
  {
    id: 'python',
    name: 'Python',
    vendor: 'Python Software Foundation',
    product: 'Python',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://www.python.org/ftp/python/',
    parserId: 'python',
    hubCategory: 'runtime',
    referenceUrl: 'https://www.python.org/',
  },
  {
    id: 'temurin',
    name: 'Eclipse Temurin (Java)',
    vendor: 'Eclipse Adoptium',
    product: 'Temurin JDK',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://api.adoptium.net/v3/',
    parserId: 'temurin',
    hubCategory: 'runtime',
    referenceUrl: 'https://adoptium.net/',
  },
  {
    id: '7zip',
    name: '7-Zip',
    vendor: 'Igor Pavlov',
    product: '7-Zip',
    category: 'A',
    supportedOs: ['Windows', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://www.7-zip.org/a/',
    parserId: '7zip',
    hubCategory: 'utility',
    referenceUrl: 'https://www.7-zip.org/',
  },
  {
    id: 'notepadpp',
    name: 'Notepad++',
    vendor: 'Don Ho',
    product: 'Notepad++',
    category: 'A',
    supportedOs: ['Windows'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://api.github.com/repos/notepad-plus-plus/notepad-plus-plus/releases/latest',
    parserId: 'github-releases',
    hubCategory: 'development',
    referenceUrl: 'https://notepad-plus-plus.org/',
  },
  {
    id: 'git',
    name: 'Git for Windows',
    vendor: 'Git SCM',
    product: 'Git',
    category: 'A',
    supportedOs: ['Windows'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://api.github.com/repos/git-for-windows/git/releases/latest',
    parserId: 'github-releases',
    hubCategory: 'development',
    referenceUrl: 'https://git-scm.com/',
  },

  // ---- Category B: Semi-Automatic ----
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    vendor: 'Microsoft',
    product: 'Visual Studio Code',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://update.code.visualstudio.com/api/releases/stable',
    parserId: 'vscode',
    hubCategory: 'development',
    referenceUrl: 'https://code.visualstudio.com/',
  },
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    vendor: 'Mozilla',
    product: 'Firefox',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'High',
    defaultCategory: 'Security Updates',
    apiUrl: 'https://product-details.mozilla.org/1.0/firefox_versions.json',
    parserId: 'firefox',
    hubCategory: 'browser',
    referenceUrl: 'https://www.mozilla.org/firefox/',
  },
  {
    id: 'vlc',
    name: 'VLC Media Player',
    vendor: 'VideoLAN',
    product: 'VLC',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://get.videolan.org/vlc/',
    parserId: 'vlc',
    hubCategory: 'media',
    referenceUrl: 'https://www.videolan.org/vlc/',
  },
  {
    id: 'virtualbox',
    name: 'VirtualBox',
    vendor: 'Oracle',
    product: 'VirtualBox',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://download.virtualbox.org/virtualbox/',
    parserId: 'virtualbox',
    hubCategory: 'development',
    referenceUrl: 'https://www.virtualbox.org/',
  },
  {
    id: 'filezilla',
    name: 'FileZilla Client',
    vendor: 'FileZilla Project',
    product: 'FileZilla',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://filezilla-project.org/download.php?show_all=1',
    parserId: 'filezilla',
    hubCategory: 'utility',
    referenceUrl: 'https://filezilla-project.org/',
  },
  {
    id: 'docker',
    name: 'Docker Desktop',
    vendor: 'Docker Inc.',
    product: 'Docker Desktop',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://download.docker.com/',
    parserId: 'docker',
    hubCategory: 'development',
    referenceUrl: 'https://www.docker.com/',
  },
  {
    id: 'wireshark',
    name: 'Wireshark',
    vendor: 'Wireshark Foundation',
    product: 'Wireshark',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://1.na.dl.wireshark.org/',
    parserId: 'wireshark',
    hubCategory: 'security',
    referenceUrl: 'https://www.wireshark.org/',
  },

  // ---- Category C: Latest Only ----
  {
    id: 'postman',
    name: 'Postman',
    vendor: 'Postman Inc.',
    product: 'Postman',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://dl.pstmn.io/download/latest/',
    parserId: 'postman',
    hubCategory: 'development',
    referenceUrl: 'https://www.postman.com/',
  },
  {
    id: 'brave',
    name: 'Brave Browser',
    vendor: 'Brave Software',
    product: 'Brave',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Security Updates',
    apiUrl: 'https://api.github.com/repos/brave/brave-browser/releases/latest',
    parserId: 'brave',
    hubCategory: 'browser',
    referenceUrl: 'https://brave.com/',
  },
  {
    id: 'slack',
    name: 'Slack',
    vendor: 'Salesforce',
    product: 'Slack',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://slack.com/ssb/download',
    parserId: 'slack',
    hubCategory: 'communication',
    referenceUrl: 'https://slack.com/',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    vendor: 'Microsoft',
    product: 'Microsoft Teams',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://www.microsoft.com/microsoft-teams/download-app',
    parserId: 'teams',
    hubCategory: 'communication',
    referenceUrl: 'https://www.microsoft.com/microsoft-teams/',
  },
  {
    id: 'discord',
    name: 'Discord',
    vendor: 'Discord Inc.',
    product: 'Discord',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://discord.com/api/downloads/distributions/app/installers/latest',
    parserId: 'discord',
    hubCategory: 'communication',
    referenceUrl: 'https://discord.com/',
  },
  {
    id: 'anydesk',
    name: 'AnyDesk',
    vendor: 'AnyDesk Software',
    product: 'AnyDesk',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://anydesk.com/en/downloads/versions',
    parserId: 'anydesk',
    hubCategory: 'utility',
    referenceUrl: 'https://anydesk.com/',
  },
  {
    id: 'teamviewer',
    name: 'TeamViewer',
    vendor: 'TeamViewer',
    product: 'TeamViewer',
    category: 'C',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://www.teamviewer.com/en-in/download/portal/',
    parserId: 'teamviewer',
    hubCategory: 'utility',
    referenceUrl: 'https://www.teamviewer.com/',
  },
  {
    id: 'opera',
    name: 'Opera',
    vendor: 'Opera Software',
    product: 'Opera',
    category: 'B',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://ftp.opera.com/ftp/pub/opera/desktop/',
    parserId: 'opera',
    hubCategory: 'browser',
    referenceUrl: 'https://www.opera.com/',
  },
  {
    id: 'winrar',
    name: 'WinRAR',
    vendor: 'RARLAB',
    product: 'WinRAR',
    category: 'A',
    supportedOs: ['Windows'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://www.rarlab.com/download.htm',
    parserId: 'winrar',
    hubCategory: 'utility',
    referenceUrl: 'https://www.rarlab.com/',
  },
  {
    id: 'anaconda',
    name: 'Anaconda',
    vendor: 'Anaconda Inc.',
    product: 'Anaconda',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://repo.anaconda.com/archive/',
    parserId: 'anaconda',
    hubCategory: 'development',
    referenceUrl: 'https://www.anaconda.com/',
  },
  {
    id: 'awscli',
    name: 'AWS CLI',
    vendor: 'Amazon Web Services',
    product: 'AWS CLI',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Low',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://awscli.amazonaws.com/',
    parserId: 'awscli',
    hubCategory: 'development',
    referenceUrl: 'https://aws.amazon.com/cli/',
  },
  {
    id: 'dotnet',
    name: '.NET Runtime',
    vendor: 'Microsoft',
    product: '.NET',
    category: 'A',
    supportedOs: ['Windows', 'MacOS', 'Linux'],
    defaultSeverity: 'Medium',
    defaultCategory: 'Application Updates',
    apiUrl: 'https://dotnet.microsoft.com/en-us/download/dotnet',
    parserId: 'dotnet',
    hubCategory: 'runtime',
    referenceUrl: 'https://dotnet.microsoft.com/',
  },
];
