/**
 * seed-patches-v2.ts — Seed patches with real CVE correlation
 *
 * Reads cve-data.json (generated by fetch-cve-data.ts) and populates:
 *   - Patch records (up to 3 versions × platforms per software)
 *   - Vulnerability records (real CVE data from NVD)
 *   - PatchVulnerability links (latest patch fixes CVEs)
 *   - PatchAffectedProduct (vulnerable software versions)
 *   - PatchFileDetail (MinIO file references)
 *   - VulnerabilityReference (NVD reference URLs)
 *   - VulnerabilitySoftware (affected CPE version ranges)
 *
 * Run:
 *   npx tsx src/db/prisma/seed-patches-v2.ts
 *
 * Prerequisites:
 *   npx tsx src/db/prisma/seeds/fetch-cve-data.ts  (generates cve-data.json)
 *   OR: cve-data.json already exists in the seeds/ directory
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import { SOFTWARE_CATALOG } from './seeds/cve-data-catalog';
import type { CveDataFile } from './seeds/fetch-cve-data';

const prisma = new PrismaClient();

// Marker to identify records created by this seed (for safe cleanup)
const SEED_SOURCE = 'seed-patches-v2';

// ─── Helpers ──────────────────────────────────────────────────────────

function makePatchId(prefix: string, platform: string, versionIdx: number): string {
  const platformSuffix = platform === 'Windows' ? '' : platform === 'MacOS' ? '-MAC' : '-LNX';
  return `${prefix}${platformSuffix}-${(versionIdx + 1).toString().padStart(4, '0')}`;
}

function maxSeverity(severities: string[]): string {
  const order: Record<string, number> = { 'CRITICAL': 4, 'High': 3, 'HIGH': 3, 'Medium': 2, 'MEDIUM': 2, 'Low': 1, 'LOW': 1 };
  let max = 0;
  let result = 'Low';
  for (const s of severities) {
    const val = order[s] || 0;
    if (val > max) {
      max = val;
      result = s;
    }
  }
  return result;
}

// ─── Cleanup ──────────────────────────────────────────────────────────

async function cleanup() {
  console.log('── Cleanup ──');

  // Delete relational records for patches created by this seed
  // We identify our patches by their source field
  const ourPatches = await prisma.patch.findMany({
    where: { source: SEED_SOURCE },
    select: { id: true, patchId: true },
  });

  if (ourPatches.length > 0) {
    const ids = ourPatches.map(p => p.id);
    console.log(`  Removing ${ourPatches.length} previously seeded patches and their relations...`);

    // Cascaded by Prisma onDelete: Cascade, but let's be explicit
    await prisma.patchVulnerability.deleteMany({ where: { patchId: { in: ids } } });
    await prisma.patchAffectedProduct.deleteMany({ where: { patchId: { in: ids } } });
    await prisma.patchFileDetail.deleteMany({ where: { patchId: { in: ids } } });
    await prisma.patch.deleteMany({ where: { source: SEED_SOURCE } });
  }

  // Delete vulnerabilities created by this seed
  const ourVulns = await prisma.vulnerability.findMany({
    where: { fixRecommendation: SEED_SOURCE },
    select: { id: true },
  });

  if (ourVulns.length > 0) {
    const vulnIds = ourVulns.map(v => v.id);
    console.log(`  Removing ${ourVulns.length} previously seeded vulnerabilities...`);
    await prisma.vulnerabilityReference.deleteMany({ where: { vulnerabilityId: { in: vulnIds } } });
    await prisma.vulnerabilitySoftware.deleteMany({ where: { vulnerabilityId: { in: vulnIds } } });
    await prisma.vulnerability.deleteMany({ where: { fixRecommendation: SEED_SOURCE } });
  }

  // Clean up SoftwarePackage records created by this seed
  const ourPackages = await prisma.softwarePackage.findMany({
    where: { createdBy: SEED_SOURCE },
    select: { id: true },
  });
  if (ourPackages.length > 0) {
    console.log(`  Removing ${ourPackages.length} previously seeded software packages...`);
    await prisma.hubBundleItem.deleteMany({ where: { packageId: { in: ourPackages.map(p => p.id) } } });
    await prisma.softwarePackage.deleteMany({ where: { createdBy: SEED_SOURCE } });
  }

  // Clean up all old seed-patches.ts patches by their known bulletin prefixes
  const oldPrefixes = [
    'NODEJS', 'GO', 'PYTHON', 'TEMURIN', 'CHROME', 'FIREFOX',
    'GIT', '7ZIP', 'NPP', 'VLC', 'FILEZILLA', 'DOCKER',
    'DISCORD', 'ANYDESK', 'POSTMAN', 'MWBYTES', 'SLACK',
    'ZOOM', 'VSCODE', 'NGINX', 'OPENSSL', 'CURL', 'SUDO', 'KERNEL',
  ];

  for (const prefix of oldPrefixes) {
    const oldPatches = await prisma.patch.findMany({
      where: {
        patchId: { startsWith: prefix },
        source: null, // Old seed didn't set source
      },
      select: { id: true },
    });
    if (oldPatches.length > 0) {
      const ids = oldPatches.map(p => p.id);
      await prisma.patchVulnerability.deleteMany({ where: { patchId: { in: ids } } });
      await prisma.patchAffectedProduct.deleteMany({ where: { patchId: { in: ids } } });
      await prisma.patchFileDetail.deleteMany({ where: { patchId: { in: ids } } });
      await prisma.patch.deleteMany({ where: { id: { in: ids } } });
      console.log(`  Cleaned up ${oldPatches.length} old patches with prefix ${prefix}`);
    }
  }

  console.log('  Cleanup complete.\n');
}

// ─── Seed Vulnerabilities ─────────────────────────────────────────────

async function seedVulnerabilities(cveDataFile: CveDataFile): Promise<Map<string, string>> {
  console.log('── Seeding Vulnerabilities ──');
  const cveToVulnId = new Map<string, string>();

  for (const [cveId, cve] of Object.entries(cveDataFile.cves)) {
    try {
      const vuln = await prisma.vulnerability.upsert({
        where: { cveId },
        update: {
          title: cve.title,
          description: cve.description,
          severity: cve.severity,
          cvss3BaseScore: cve.cvss3BaseScore,
          cvss3VectorString: cve.cvss3VectorString,
          cvss3AttackVector: cve.cvss3AttackVector,
          cvss3AttackComplexity: cve.cvss3AttackComplexity,
          cvss3PrivilegesRequired: cve.cvss3PrivilegesRequired,
          cvss3Scope: cve.cvss3Scope,
          cvss3Confidentiality: cve.cvss3Confidentiality,
          cvss3Integrity: cve.cvss3Integrity,
          cvss3Availability: cve.cvss3Availability,
          cvss3ImpactScore: cve.cvss3ImpactScore,
          cvss2BaseScore: cve.cvss2BaseScore,
          cvss2Severity: cve.cvss2Severity,
          epss: cve.epss,
          riskScore: cve.cvss3BaseScore ? cve.cvss3BaseScore * 10 : null,
          publishedDate: new Date(cve.publishedDate),
          lastModified: new Date(cve.lastModified),
          patchAvailable: true,
          exploitable: false,
          isZeroDay: false,
          fixRecommendation: SEED_SOURCE,
        },
        create: {
          cveId,
          title: cve.title,
          description: cve.description,
          severity: cve.severity,
          cvss3BaseScore: cve.cvss3BaseScore,
          cvss3VectorString: cve.cvss3VectorString,
          cvss3AttackVector: cve.cvss3AttackVector,
          cvss3AttackComplexity: cve.cvss3AttackComplexity,
          cvss3PrivilegesRequired: cve.cvss3PrivilegesRequired,
          cvss3Scope: cve.cvss3Scope,
          cvss3Confidentiality: cve.cvss3Confidentiality,
          cvss3Integrity: cve.cvss3Integrity,
          cvss3Availability: cve.cvss3Availability,
          cvss3ImpactScore: cve.cvss3ImpactScore,
          cvss2BaseScore: cve.cvss2BaseScore,
          cvss2Severity: cve.cvss2Severity,
          epss: cve.epss,
          riskScore: cve.cvss3BaseScore ? cve.cvss3BaseScore * 10 : null,
          publishedDate: new Date(cve.publishedDate),
          lastModified: new Date(cve.lastModified),
          patchAvailable: true,
          exploitable: false,
          isZeroDay: false,
          fixRecommendation: SEED_SOURCE,
        },
      });

      cveToVulnId.set(cveId, vuln.id);

      // Seed VulnerabilityReference records
      for (const ref of cve.references) {
        await prisma.vulnerabilityReference.create({
          data: {
            vulnerabilityId: vuln.id,
            url: ref.url,
            source: ref.source,
          },
        });
      }

      // Seed VulnerabilitySoftware records from affected version ranges
      for (const range of cve.affectedVersionRanges) {
        await prisma.vulnerabilitySoftware.create({
          data: {
            vulnerabilityId: vuln.id,
            name: range.cpeProduct,
            vendor: range.cpeVendor,
            cpeUri: range.cpeUri,
            cpeVendor: range.cpeVendor,
            cpeProduct: range.cpeProduct,
            versionStart: range.versionStart,
            versionEnd: range.versionEnd,
            versionStartType: range.versionStartType,
            versionEndType: range.versionEndType,
          },
        });
      }

      console.log(`  ${cveId}: CVSS3=${cve.cvss3BaseScore ?? 'N/A'} EPSS=${cve.epss?.toFixed(2) ?? 'N/A'}%`);
    } catch (err: any) {
      console.error(`  [ERROR] ${cveId}: ${err.message}`);
    }
  }

  console.log(`  Seeded ${cveToVulnId.size} vulnerabilities\n`);
  return cveToVulnId;
}

// ─── Seed Patches ─────────────────────────────────────────────────────

async function seedPatches(cveDataFile: CveDataFile, cveToVulnId: Map<string, string>) {
  console.log('── Seeding Patches ──');
  let patchCount = 0;
  let pvCount = 0;
  let apCount = 0;
  let fdCount = 0;

  for (const sw of SOFTWARE_CATALOG) {
    const swCveData = cveDataFile.software[sw.name];
    const cveIds = swCveData?.cves || [];
    const cves = cveIds.map(id => cveDataFile.cves[id]).filter(Boolean);

    for (const platform of sw.platforms) {
      const arch = platform === 'MacOS' ? 'Universal' : '64 BIT';

      for (let vi = 0; vi < sw.versions.length; vi++) {
        const ver = sw.versions[vi];
        const isLatest = ver.label === 'latest';
        const isN1 = ver.label === 'n-1';

        const pid = makePatchId(sw.bulletinPrefix, platform, vi);
        const patchCves = isLatest ? cveIds : []; // Only latest patch "fixes" CVEs

        // Determine severity from associated CVEs
        let severity = 'Low';
        if (isLatest && cves.length > 0) {
          severity = maxSeverity(cves.map(c => c.severity));
        } else if (isN1) {
          // N-1 may still be partially vulnerable
          severity = cves.length > 0 ? 'Medium' : 'Low';
        }

        // Determine status/approval based on version tier
        const status = isLatest ? 'Published' : (isN1 ? 'Published' : 'Superseded');
        const testStatus = isLatest ? 'Tested' : (isN1 ? 'Tested' : 'Not Tested');
        const approvalStatus = 'Approved';

        // Supersession chain
        const prevPid = vi < sw.versions.length - 1 ? makePatchId(sw.bulletinPrefix, platform, vi + 1) : null;
        const nextPid = vi > 0 ? makePatchId(sw.bulletinPrefix, platform, vi - 1) : null;

        const description = isLatest && cveIds.length > 0
          ? `${sw.name} ${ver.version} - security update fixing ${cveIds.length} CVE(s): ${cveIds.join(', ')}`
          : `${sw.name} ${ver.version} for ${platform}`;

        try {
          const patch = await prisma.patch.create({
            data: {
              patchId: pid,
              title: `${sw.name} ${ver.version}`,
              software: `${sw.name} ${ver.version}`,
              description,
              severity,
              category: sw.category,
              vendor: sw.vendor,
              product: sw.product,
              os: platform,
              platform,
              architecture: arch,
              kbNumber: pid,
              bulletinId: `${sw.bulletinPrefix}-${ver.version.replace(/[^a-zA-Z0-9]/g, '-')}`,
              releaseDate: new Date(ver.releaseDate),
              referenceUrl: sw.referenceUrl,
              downloadUrl: '',
              rebootRequired: sw.rebootRequired,
              supportUninstallation: sw.supportUninstallation,
              languagesSupported: ['English'],
              tags: sw.tags,
              cveNumbers: patchCves,
              status,
              downloadStatus: 'Downloaded',
              testStatus,
              approvalStatus,
              supersedes: prevPid ? [prevPid] : [],
              supersededBy: nextPid ? [nextPid] : [],
              endpoints: Math.floor(Math.random() * 40) + 5,
              operationalStatusSince: new Date(ver.releaseDate),
              source: SEED_SOURCE,
            },
          });
          patchCount++;

          const tag = isLatest ? '[LATEST]' : (isN1 ? '[N-1]   ' : '[N-2]   ');
          console.log(`  ${tag} ${pid.padEnd(25)} ${sw.name.padEnd(25)} ${ver.version.padEnd(15)} ${platform.padEnd(8)} ${severity.padEnd(10)}`);

          // ── PatchVulnerability: Link latest patch to CVEs it fixes
          if (isLatest) {
            for (const cveId of cveIds) {
              const cveData = cveDataFile.cves[cveId];
              if (!cveData) continue;

              await prisma.patchVulnerability.create({
                data: {
                  patchId: patch.id,
                  cveNumber: cveId,
                  severity: cveData.severity,
                  description: cveData.description.substring(0, 500),
                  publishedDate: new Date(cveData.publishedDate),
                },
              });
              pvCount++;
            }
          }

          // ── PatchAffectedProduct: The old vulnerable versions this patch targets
          if (isLatest && swCveData) {
            // For each CVE, add affected product entries
            const seenProducts = new Set<string>();
            for (const cveId of cveIds) {
              const affectedVer = swCveData.affectedVersions[cveId];
              const productKey = `${sw.name}:${affectedVer?.end || 'unknown'}:${platform}`;
              if (seenProducts.has(productKey)) continue;
              seenProducts.add(productKey);

              await prisma.patchAffectedProduct.create({
                data: {
                  patchId: patch.id,
                  softwareName: sw.name,
                  version: affectedVer?.end || sw.versions.find(v => v.label === 'n-1')?.version || 'unknown',
                  vendor: sw.vendor,
                  platform,
                  installedOn: Math.floor(Math.random() * 30) + 5,
                },
              });
              apCount++;
            }
          }

          // ── PatchFileDetail: MinIO file reference
          const fileKey = `${platform}:${ver.version}`;
          const minioRef = sw.minioFiles[fileKey];
          if (minioRef) {
            await prisma.patchFileDetail.create({
              data: {
                patchId: patch.id,
                fileName: minioRef.fileName,
                version: ver.version,
                path: minioRef.key,
                minioObjectKey: minioRef.key,
                minioBucket: 'patches',
                downloadStatus: 'completed',
                downloadedAt: new Date(),
                sourceUrl: sw.referenceUrl,
              },
            });
            fdCount++;
          }
        } catch (err: any) {
          if (err.code === 'P2002') {
            console.log(`  [SKIP]  ${pid} already exists`);
          } else {
            console.error(`  [ERROR] ${pid}: ${err.message}`);
          }
        }
      }
    }
  }

  console.log(`\n  Summary:`);
  console.log(`    Patches created: ${patchCount}`);
  console.log(`    PatchVulnerability links: ${pvCount}`);
  console.log(`    PatchAffectedProduct entries: ${apCount}`);
  console.log(`    PatchFileDetail entries: ${fdCount}`);
}

// ─── Seed Software Packages (Hub) ────────────────────────────────────

async function seedSoftwarePackages() {
  console.log('\n── Seeding Software Packages (Hub) ──');
  let count = 0;

  for (const sw of SOFTWARE_CATALOG) {
    for (const platform of sw.platforms) {
      for (const ver of sw.versions) {
        const fileKey = `${platform}:${ver.version}`;
        const minioRef = sw.minioFiles[fileKey];

        // Determine install source based on file extension
        let installSource = 'url';
        if (minioRef) {
          const fn = minioRef.fileName.toLowerCase();
          if (fn.endsWith('.msi')) installSource = 'msi';
          else if (fn.endsWith('.exe')) installSource = 'exe';
          else if (fn.endsWith('.pkg')) installSource = 'pkg';
          else if (fn.endsWith('.dmg')) installSource = 'dmg';
          else if (fn.endsWith('.deb')) installSource = 'deb';
          else if (fn.endsWith('.rpm')) installSource = 'rpm';
          else if (fn.endsWith('.tar.xz') || fn.endsWith('.tar.gz')) installSource = 'archive';
        }

        const platformLower = platform.toLowerCase();
        const packageId = `SWP-${sw.bulletinPrefix}-${platformLower.slice(0, 3).toUpperCase()}-${ver.version.replace(/[^a-zA-Z0-9]/g, '-')}`;

        try {
          await prisma.softwarePackage.create({
            data: {
              packageId,
              name: sw.name,
              displayName: `${sw.name} ${ver.version}`,
              version: ver.version,
              vendor: sw.vendor,
              category: sw.category,
              platform: platformLower,
              architecture: platform === 'MacOS' ? 'universal' : 'x64',
              installSource,
              silentInstall: true,
              requiresReboot: sw.rebootRequired,
              requiresRoot: platformLower !== 'windows',

              // MinIO storage
              minioObjectKey: minioRef?.key || null,
              minioBucket: minioRef ? 'patches' : null,
              fileName: minioRef?.fileName || null,

              // External URL fallback
              downloadUrl: sw.referenceUrl,

              // Metadata
              description: `${sw.name} ${ver.version} for ${platform} (${ver.label})`,
              tags: [...sw.tags, ver.label, platform.toLowerCase()],

              supportsRollback: ver.label !== 'n-2',
              isActive: ver.label !== 'n-2',
              isVerified: ver.label === 'latest',
              createdBy: SEED_SOURCE,
            },
          });
          count++;
        } catch (err: any) {
          if (err.code === 'P2002') {
            console.log(`  [SKIP]  ${packageId} already exists`);
          } else {
            console.error(`  [ERROR] ${packageId}: ${err.message}`);
          }
        }
      }
    }
  }

  console.log(`  Seeded ${count} software packages for Hub`);
}

// ─── Main ─────────────────────────────────────────────────────────────

async function main() {
  console.log('=== Patch Seed v2: Real CVE Correlation ===\n');

  // Load CVE data
  const cveDataPath = path.join(__dirname, 'seeds', 'cve-data.json');
  if (!fs.existsSync(cveDataPath)) {
    console.error(`Error: ${cveDataPath} not found.`);
    console.error('Run first: npx tsx src/db/prisma/seeds/fetch-cve-data.ts');
    process.exit(1);
  }

  const cveDataFile: CveDataFile = JSON.parse(fs.readFileSync(cveDataPath, 'utf-8'));
  console.log(`Loaded cve-data.json (fetched: ${cveDataFile.fetchedAt})`);
  console.log(`  Software: ${Object.keys(cveDataFile.software).length}`);
  console.log(`  CVEs: ${Object.keys(cveDataFile.cves).length}\n`);

  // Step 1: Cleanup previous seed data
  await cleanup();

  // Step 2: Seed vulnerabilities
  const cveToVulnId = await seedVulnerabilities(cveDataFile);

  // Step 3: Seed patches with full relational data
  await seedPatches(cveDataFile, cveToVulnId);

  // Step 4: Seed SoftwarePackage records for Hub
  await seedSoftwarePackages();

  console.log('\n=== Done ===');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
